version: "3.3"
services:
  app:
    image: clemenko/fedsummit_2018
    deploy:
      replicas: 2
      mode: replicated
      placement:
        constraints:
          - 'node.role == worker'
    ports:
      - 5000:5000
    secrets:
      - source: title_v1
        target: secret

secrets:
  title_v1:
    external: true
